variables:
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA #unix id
  TAG_JAR: "jar"
  TAG_NGINX: "nginx"

stages:
  - build-jar
  - deploy_to_production

buildJar:
  stage: build-jar
  tags:
    - spring
  only:
    - /^live_[0-9]+(?:.[0-9]+)+$/ # regular expression live_0.0.1, live_0.0.2, live_0.0.3, etc.
  artifacts:
    paths:
      - target/spring-boot.jar
  script:
    - echo "Building jar"
    - mvn clean install -DskipTests
    - echo "Jar built Success"
    - echo "Build Docker Image"
    - docker build -t $TAG_COMMIT$TAG_JAR . #build docker jar build
    - docker build -t $TAG_COMMIT$TAG_NGINX ./nginx #build docker jar build
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY #login vào docker registry
    - docker push $TAG_COMMIT$TAG_JAR #push docker image lên registry
    - docker push $TAG_COMMIT$TAG_NGINX



deploy:
  stage: deploy_to_production
  image: alpine:latest #linux
  tags:
    - docker
  only:
    - /^live_[0-9]+(?:.[0-9]+)+$/ # regular expression live_0.0.1, live_0.0.2, live_0.0.3, etc.
  script:
    - echo "Deploy to production"
    - echo $SERVER_USER
    - echo $GITLAB_CI_SSH_KEY
    - chmod 600 $GITLAB_CI_SSH_KEY #chmod og= cho key
    - apk update && apk add openssh-client #cài đặt package openssh-client
    #- ssh -o StrictHostKeyChecking=no -i $GITLAB_CI_SSH_KEY $SERVER_USER@$SERVER_HOST #run list
    - ssh -i $GITLAB_CI_SSH_KEY -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "docker ps"
    - ssh -i $GITLAB_CI_SSH_KEY -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY" #login vào registry
    - ssh -i $GITLAB_CI_SSH_KEY -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "docker pull $TAG_COMMIT$TAG_JAR" #pull docker image về server
    - ssh -i $GITLAB_CI_SSH_KEY -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "docker container rm -f spring-boot-app || true" #xoá ảnh cũ có tên là html-app đi
    - ssh -i $GITLAB_CI_SSH_KEY -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "docker run -d --name spring-boot-app -p 9998:9998 --network="host" $TAG_COMMIT$TAG_JAR || true" #run docker image với tên là html-app
    - ssh -i $GITLAB_CI_SSH_KEY -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "docker pull $TAG_COMMIT$TAG_NGINX" #pull docker image về server
    - ssh -i $GITLAB_CI_SSH_KEY -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "docker container rm -f nginx || true" #xoá ảnh cũ có tên là html-app đi
    - ssh -i $GITLAB_CI_SSH_KEY -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "docker run -d --name nginx -p 80:80 --network="host" $TAG_COMMIT$TAG_NGINX" #run docker image với tên là html-app
  environment:
    name: production
    url: http://$SERVER_HOST #url của server chạy web
